### PR TITLE
Fixes defaults extensibility in configuration files

### LINKED ISSUE #34: Error: cannot read config file
I think this problem may interest you https://github.com/AtomLinter/linter-eslint/issues/213

### PR DESCRIPTION
**Pull request by chaseadamsio**
Dug through `eslint/eslint` and found that the way extensibility works doesn't relative paths into consideration, it automatically assumes the `eslint-config` as the "root" and just joins the path based on the shared configuration.

### Testing:

Confirmed a local `.eslintrc` extending `defaults` and `defaults/*` did linting without errors in:
- Atom
- Shell running `node ./node_modules/eslint`

@ryan-roemer @baer 

Closes #34.

### CODE REVIEW

**Comment by divmain** [comment]
Nice find!

File: rules/eslint/best-practices/eslint.js [hunk 1]
```diff
@@ -1,5 +1,3 @@
-"use strict";
```
Comment (ryan-roemer) [inline rules/eslint/best-practices/eslint.js]: What happened with this one?

**Comment by ryan-roemer** [comment]
@chaseadamsio -- Nice work! This configuration now works for me:

```
{
  "extends": "defaults"
}
```

One question, rest LGTM!

File: rules/eslint/best-practices/eslint.js (hunk 1 above)
Comment (chaseadamsio) [inline rules/eslint/best-practices/eslint.js]: Added it back, accidentally removed it during my "I wonder if this has anything to do with it" testing.

**Comment by baer** [comment]
The way eslint pulls in config is a little wonky. Great find! Thanks!

**Comment by chaseadamsio** [comment]
@baer, can you bump the version?

**Comment by baer** [comment]
Yes, I'll rev the version after I do a bit of testing - expect it today.
